version: "3.8"

services:

  catalog-service-transformer:
    build:
      context: .
      dockerfile: dockerfiles/transformerDockerfile
    container_name: catalog-service-transformer
    restart: always
    depends_on:
      - rabbitmq
      - mongo
    environment:
      ENV: dev
      MONGO_DATABASE_URL: "mongodb://mongo:27017"
      ELASTIC_SEARCH_URL: "http://elasticsearch:9200"
      RABBITMQ_HOST: "rabbitmq"
      LANGUAGE_LIST: ${LANGUAGE_LIST}

  catalog-service-es-dumper:
    build:
      context: .
      dockerfile: dockerfiles/esDumperDockerfile
    container_name: catalog-service-es-dumper
    restart: always
    depends_on:
      - elasticsearch
      - rabbitmq
    environment:
      ENV: dev
      RABBITMQ_HOST: "rabbitmq"
      ELASTIC_SEARCH_URL: "http://elasticsearch:9200"

  catalog-service-translator:
    build:
      context: .
      dockerfile: dockerfiles/translatorDockerfile
    container_name: catalog-service-translator
    restart: always
    depends_on:
      - rabbitmq
    environment:
      ENV: dev
      RABBITMQ_HOST: "rabbitmq"
      MONGO_DATABASE_URL: "mongodb://mongo:27017"
      BHASHINI_USERID: ${BHASHINI_USERID}
      BHASHINI_ULCA_API_KEY: ${BHASHINI_ULCA_API_KEY}
      REDIS_HOST: "cache"

  rabbitmq:
    image: rabbitmq:3.10-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - "./data:/data/db"

  elasticsearch:
    image: elasticsearch:8.8.0
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx3g"  # Adjust as per your server resources
      - "http.max_content_length=200mb"  # Adjust based on your payload size
    volumes:
      - "./es_data:/usr/share/elasticsearch/data"

#  kibana:
#    image: kibana:8.12.2
#    container_name: kibana
#    ports:
#      - "5601:5601"
#    environment:
#      ELASTICSEARCH_URL: http://elasticsearch:9200
